export const GET_TASKS = "GET_TASKS"
export const GET_TASK = "GET_TASK"
export const ADD_TASK = "ADD_TASK"
export const CHANGE_TO_DOING = "CHANGE_TO_DOING"
export const CHANGE_TO_DONE = "CHANGE_TO_DONE"
export const SHOW_DOING = "SHOW_DOING"
export const SHOW_DONE = "SHOW_DONE"
export const SHOW_TO_DO = "SHOW_TO_DO"